{% set name = "grplot" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grplot-{{ version }}.tar.gz
  sha256: ab0989339f7ada48da2b72846d9a777a0b5e1c0a5332de6bb9fcc61677d7e11b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.15
    - scipy >=1.0
    - matplotlib-base >=2.2
    - pandas >=0.23
    - ipython >=6.0

test:
  imports:
    - grplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ghiffaryr/grplot
  summary: 'grplot: lazy statistical data visualization'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
