{% set name = "grplot" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grplot-{{ version }}.tar.gz
  sha256: 87188afe92667554f79f2123c5010561ada368259c5fc22736ade31cdf57a901

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20,!=1.24.0
    - scipy >=1.0
    - matplotlib-base >=3.4,!=3.6.1
    - pandas >=1.2
    - ipython >=6.0
    - seaborn

test:
  imports:
    - grplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ghiffaryr/grplot
  summary: 'grplot: lazy statistical data visualization'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
