{% set name = "grplot" %}
{% set version = "0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grplot-{{ version }}.tar.gz
  sha256: e4bdddfef6376f0f7c59af78c4c6a2514fda2faee9ced9721fe9da2b1befc685

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - scipy >=1.0
    - matplotlib-base >=2.2,<4
    - pandas >=0.23,<1.6
    - ipython >=6.0

test:
  imports:
    - grplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ghiffaryr/grplot
  summary: 'grplot: lazy statistical data visualization'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
