{% set name = "grplot" %}
{% set version = "0.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grplot-{{ version }}.tar.gz
  sha256: bff06d1f596cd3f799468219927c109e37b1c7a0b06795d7a0c5c787f0ca9095

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15,<1.27
    - scipy >=1.0
    - matplotlib-base >=2.2,<3.8
    - pandas >=0.23,<1.6
    - ipython >=6.0
    - seaborn

test:
  imports:
    - grplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ghiffaryr/grplot
  summary: 'grplot: lazy statistical data visualization'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
